### ISSUE TITLE
What is the format of $ldap_maps?

### ISSUE THREAD

**Issue by bschonec** [geekix/puppet-nslcd#12]
Can someone give me an example of $ldap_maps format?

I've tried:
`
  $ldap_maps =  { group  => 'uniqueMember member',
                  passwd => ['homedirectory unixHomeDirectory', 'uid sAMAccountName', 'gecos displayName', ],
                  shadow => ['shadowLastChange pwdLastSet', 'uid sAMAccountName', ],
                }
`

...but the module incorrectly updates /etc/nslcd.conf thusly:

 # Custom maps
map group uniqueMember member
map passwd ["homedirectory unixHomeDirectory", "uid sAMAccountName", "gecos displayName"]
map shadow ["shadowLastChange pwdLastSet", "uid sAMAccountName"]

**Comment by hdep** [comment]
Hello,

this is an array, it works for me like this : 
ldap_maps => {'passwd' => 'uid sAMAccountName', }

hope this help

**Comment by hdep** [comment]
the only way I found is to modify  nslcd.erb : 

```
<% if @ldap_maps.length > 0 -%>
# Custom maps
<% @ldap_maps.sort.each do |key, value| -%>
map <%= value %>
<% end -%>
<% end -%>
```

and then call it with : 

```
 ldap_maps => {'1' => 'passwd uid sAMAccountName', 
	 '2' => 'passwd gecos displayName',
	 '3' => 'shadow uid  sAMAccountName',
	 '4' => 'shadow shadowLastChange pwdLastSet',
   }
```

I don't think this is the best thing to do, (I'm not a puppet code expert), but it does the job.
I hope someone will have a look at this.

**Comment by geekix** [comment]
The PR was merged, a new version will be released on the puppet forge soon.

If you are using hiera, it may look like this :

nslcd::ldap_maps:
  passwd:
    uid:  sAMAccountName

Otherwise, I think this should do the trick :

ldap_maps => {
    'passwd' => {
        'uid' => 'sAMAccountName',
        'gecos' => 'displayName',
        'shadowLastChange' => 'pwdLastSet',
    }
}
